general:
  cfApiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
  cfOrg: 'csw-qa-aws'
  cfSpace: 'qa'
  cfCredentialsId: 'cfAuthentification'
  cfServiceInstance: 'abap-qa'
stages:
  Clone Repositories:
    repositories: 'repositories.yml'
    strategy: 'Pull'
  ATC:
    # In order to be executed, the ATC stage needs at least one configuration entry
    # If the ATC stage should not be executed, delete the whole section
    execute: stage
  AUnit:
    # In order to be executed, the AUnit stage needs at least one configuration entry
    # If the AUnit stage should not be executed, delete the whole section
    execute: stage
